# Semana 1: SQL desde los fundamentos hasta Window Functions

## Roadmap del notebook

| Bloque | Qué aprenderás |
|--------|-----------------|
| 1. Setup | Conexión a PostgreSQL |
| 2. SELECT básico | Leer datos de una tabla |
| 3. WHERE y ORDER BY | Filtrar y ordenar |
| 4. Aggregaciones | COUNT, SUM, AVG, GROUP BY |
| 5. JOINs | Combinar datos de varias tablas |
| 6. Star Schema | Entender nuestro modelo de datos EUR-Lex |
| 7. Window Functions | ROW_NUMBER, RANK, LAG, SUM OVER |
| 8. CTEs | Common Table Expressions |
| 9. CTEs Recursivos | Recorrer grafos en SQL |
| 10. EXPLAIN ANALYZE | Optimizar queries |
| 11. Ejercicios | Práctica libre |

---
## 1. Setup — Conexión a PostgreSQL

In [1]:
import sqlalchemy as sa  # Librería para conectarse a bases de datos desde Python
import pandas as pd       # Librería para trabajar con tablas (DataFrames)

# Creamos la conexión a PostgreSQL.
# Formato: "tipo_db://usuario:contraseña@host:puerto/nombre_base_datos"
engine = sa.create_engine("postgresql+psycopg2://eugraphrag:eugraphrag@localhost:5432/eurlex")

def sql(query: str) -> pd.DataFrame:
    """Ejecuta una query SQL y devuelve el resultado como tabla de pandas."""
    with engine.connect() as conn:
        return pd.read_sql(sa.text(query), conn)

def sql_explain(query: str) -> None:
    """Muestra el plan de ejecución de una query (cómo PostgreSQL la resuelve internamente)."""
    with engine.connect() as conn:
        result = conn.execute(sa.text(f"EXPLAIN ANALYZE {query}"))
        for row in result:
            print(row[0])

# Verificamos que la conexión funciona
sql("SELECT 1 AS test")
# Debería devolver una tabla con una columna 'test' y valor 1

   test
0     1

---
## 2. SELECT — Leer datos de una tabla

**`SELECT`** es el comando más básico de SQL. Le dice a la base de datos: "dame estos datos".

```sql
SELECT columnas FROM tabla
```

Es como hacer `df[['col1', 'col2']]` en pandas.

In [2]:
# SELECT * = "selecciona TODAS las columnas"
# FROM dim_document_type = "de la tabla dim_document_type"
# Esta tabla contiene los tipos de documento legislativo de la UE
sql("SELECT * FROM dim_document_type")

,type_id,type_code,type_name,description
0,1,REG,Regulation,Directly applicable in all member states witho...
1,2,DIR,Directive,Sets goals that member states must achieve thr...
2,3,DEC,Decision,"Binding on specific addressees (member states,..."
3,4,REC,Recommendation,Non-binding guidance suggesting a course of ac...
4,5,OPI,Opinion,Non-binding statement by an EU institution

In [3]:
# Podemos seleccionar solo las columnas que nos interesan
# en vez de * (todas)
sql("""
    SELECT type_code, type_name    -- solo estas dos columnas
    FROM dim_document_type         -- de esta tabla
""")

  type_code       type_name
0       REG      Regulation
1       DIR       Directive
2       DEC        Decision
3       REC  Recommendation
4       OPI         Opinion

In [4]:
# LIMIT N = "dame solo las primeras N filas"
# Útil para explorar tablas grandes sin cargar todo
sql("""
    SELECT *                       -- todas las columnas
    FROM fact_documents            -- de la tabla principal de documentos
    LIMIT 5                        -- solo las primeras 5 filas
""")

,document_id,celex_number,title,publication_date_key,type_id,institution_id,article_count,text_length,reference_count,amendment_count
0,1,32019R0631,CO2 emission performance standards for new pas...,20190417,1,7,25,48000,12,3
1,2,32019L0790,Directive on copyright in the Digital Single M...,20190517,2,7,32,62000,18,1
2,3,32019L0882,European Accessibility Act,20190617,2,7,45,71000,15,0
3,4,32019R0881,ENISA and ICT cybersecurity certification (Cyb...,20190617,1,7,69,95000,22,2
4,5,32019L0944,Common rules for the internal market for elect...,20190614,2,7,72,110000,35,4

In [5]:
# Podemos renombrar columnas en el resultado con AS (alias)
sql("""
    SELECT
        celex_number AS codigo,    -- renombra 'celex_number' a 'codigo' en el resultado
        title AS titulo,           -- renombra 'title' a 'titulo'
        article_count AS num_articulos
    FROM fact_documents
    LIMIT 5
""")

,codigo,titulo,num_articulos
0,32019R0631,CO2 emission performance standards for new pas...,25
1,32019L0790,Directive on copyright in the Digital Single M...,32
2,32019L0882,European Accessibility Act,45
3,32019R0881,ENISA and ICT cybersecurity certification (Cyb...,69
4,32019L0944,Common rules for the internal market for elect...,72

---
## 3. WHERE y ORDER BY — Filtrar y ordenar

- **`WHERE`** = filtrar filas (como `df[df['col'] > 5]` en pandas)
- **`ORDER BY`** = ordenar resultados (como `df.sort_values()` en pandas)

In [6]:
# WHERE filtra las filas que cumplen una condición
sql("""
    SELECT celex_number, title, article_count
    FROM fact_documents
    WHERE article_count > 50       -- solo documentos con más de 50 artículos
""")

,celex_number,title,article_count
0,32019R0881,ENISA and ICT cybersecurity certification (Cyb...,69
1,32019L0944,Common rules for the internal market for elect...,72
2,32020R1503,European Crowdfunding Service Providers regula...,51
3,32021R0694,Horizon Europe implementation,55
4,32021R1060,Common Provisions Regulation for EU funds 2021...,115
5,32021R2115,CAP Strategic Plans regulation,148
6,32021R2116,"Financing, management and monitoring of the CAP",102
7,32022R2065,Digital Services Act,93
8,32022R1925,Digital Markets Act,54
9,32022R2560,Markets in Crypto-Assets Regulation (MiCA),149
10,32023R0988,Ecodesign for Sustainable Products Regulation,68
11,32024R1689,Artificial Intelligence Act (AI Act),113
12,32024R0903,European Health Data Space regulation,72
13,32024R1735,Cyber Resilience Act,58
14,32024R2847,Packaging and Packaging Waste Regulation,65
15,32025R0301,EU Space Law regulation,55

In [7]:
# ORDER BY ordena los resultados
# DESC = descendente (mayor a menor), ASC = ascendente (menor a mayor, es el default)
sql("""
    SELECT celex_number, title, article_count
    FROM fact_documents
    WHERE article_count > 50       -- filtrar: solo más de 50 artículos
    ORDER BY article_count DESC    -- ordenar: de mayor a menor
""")

,celex_number,title,article_count
0,32022R2560,Markets in Crypto-Assets Regulation (MiCA),149
1,32021R2115,CAP Strategic Plans regulation,148
2,32021R1060,Common Provisions Regulation for EU funds 2021...,115
3,32024R1689,Artificial Intelligence Act (AI Act),113
4,32021R2116,"Financing, management and monitoring of the CAP",102
5,32022R2065,Digital Services Act,93
6,32024R0903,European Health Data Space regulation,72
7,32019L0944,Common rules for the internal market for elect...,72
8,32019R0881,ENISA and ICT cybersecurity certification (Cyb...,69
9,32023R0988,Ecodesign for Sustainable Products Regulation,68
10,32024R2847,Packaging and Packaging Waste Regulation,65
11,32024R1735,Cyber Resilience Act,58
12,32025R0301,EU Space Law regulation,55
13,32021R0694,Horizon Europe implementation,55
14,32022R1925,Digital Markets Act,54
15,32020R1503,European Crowdfunding Service Providers regula...,51

In [8]:
# Se pueden combinar condiciones con AND / OR
sql("""
    SELECT celex_number, title, article_count, text_length
    FROM fact_documents
    WHERE article_count > 30       -- más de 30 artículos
      AND text_length > 80000      -- Y además texto de más de 80.000 caracteres
    ORDER BY text_length DESC      -- ordenar por longitud de texto, mayor primero
""")

,celex_number,title,article_count,text_length
0,32022R2560,Markets in Crypto-Assets Regulation (MiCA),149,230000
1,32021R2115,CAP Strategic Plans regulation,148,220000
2,32024R1689,Artificial Intelligence Act (AI Act),113,190000
3,32021R1060,Common Provisions Regulation for EU funds 2021...,115,180000
4,32021R2116,"Financing, management and monitoring of the CAP",102,165000
5,32022R2065,Digital Services Act,93,145000
6,32024R0903,European Health Data Space regulation,72,120000
7,32019L0944,Common rules for the internal market for elect...,72,110000
8,32024R2847,Packaging and Packaging Waste Regulation,65,108000
9,32023R0988,Ecodesign for Sustainable Products Regulation,68,105000
10,32022R1925,Digital Markets Act,54,98000
11,32024R1735,Cyber Resilience Act,58,95000
12,32019R0881,ENISA and ICT cybersecurity certification (Cyb...,69,95000
13,32023L2413,Renewable Energy Directive (RED III),38,92000
14,32025R0301,EU Space Law regulation,55,90000
15,32023R2854,Data Act,50,88000
16,32021R0694,Horizon Europe implementation,55,88000
17,32023L1791,Energy Efficiency Directive (recast),40,85000
18,32024R1781,Critical Raw Materials Act,47,82000
19,32021R0695,Horizon Europe Framework Programme,48,82000

In [9]:
# LIKE busca patrones en texto
# '%' = cualquier texto (como * en búsqueda de archivos)
sql("""
    SELECT celex_number, title
    FROM fact_documents
    WHERE title LIKE '%Climate%'   -- títulos que contengan la palabra 'Climate'
""")

  celex_number                 title
0   32021R1119  European Climate Law

---
## 4. Agregaciones — COUNT, SUM, AVG, GROUP BY

Las funciones de agregación colapsan múltiples filas en una sola:
- **`COUNT(*)`** = contar filas
- **`SUM(col)`** = sumar valores
- **`AVG(col)`** = calcular la media
- **`MIN(col)`** / **`MAX(col)`** = mínimo / máximo

**`GROUP BY`** agrupa filas antes de agregar. Es como `df.groupby('col').agg(...)` en pandas.

Sin `GROUP BY`, la agregación se aplica a TODA la tabla.

In [10]:
# Sin GROUP BY: una sola fila con el total
sql("""
    SELECT
        COUNT(*) AS total_documentos,               -- cuenta todas las filas
        AVG(article_count) AS media_articulos,      -- media de artículos
        MAX(article_count) AS max_articulos,        -- documento con más artículos
        SUM(text_length) AS texto_total              -- suma de toda la longitud de texto
    FROM fact_documents
""")

   total_documentos  media_articulos  max_articulos  texto_total
0                58        44.155172            149      4267000

In [11]:
# Con GROUP BY: una fila POR CADA grupo
# Aquí agrupamos por type_id (tipo de documento)
sql("""
    SELECT
        type_id,                                    -- la columna por la que agrupamos
        COUNT(*) AS num_documentos,                 -- cuántos documentos hay de cada tipo
        AVG(article_count)::INTEGER AS media_articulos  -- media de artículos por tipo
                                                    -- ::INTEGER convierte el resultado a entero
    FROM fact_documents
    GROUP BY type_id                                -- "agrupa las filas por type_id"
    ORDER BY num_documentos DESC                    -- ordena por cantidad, mayor primero
""")

   type_id  num_documentos  media_articulos
0        1              43               48
1        2              15               33

In [12]:
# HAVING = es como WHERE pero para filtrar DESPUÉS de agrupar
# WHERE filtra filas individuales ANTES de agrupar
# HAVING filtra grupos DESPUÉS de agrupar
sql("""
    SELECT
        type_id,
        COUNT(*) AS num_documentos
    FROM fact_documents
    GROUP BY type_id
    HAVING COUNT(*) > 5            -- solo mostrar tipos con más de 5 documentos
""")

   type_id  num_documentos
0        1              43
1        2              15

---
## 5. JOINs — Combinar datos de varias tablas

Un **JOIN** conecta dos tablas usando una columna que tienen en común. Es como `pd.merge()` en pandas.

```sql
SELECT ...
FROM tabla_a
JOIN tabla_b ON tabla_a.columna = tabla_b.columna
```

### Tipos de JOIN
```
INNER JOIN  → solo filas que coinciden en AMBAS tablas (el más común, es el default)
LEFT JOIN   → TODAS las filas de la tabla izquierda + las que coincidan de la derecha
RIGHT JOIN  → al revés que LEFT
FULL JOIN   → TODAS las filas de ambas tablas
```

Ejemplo visual:
```
fact_documents tiene type_id = 1, 2, 3...
dim_document_type tiene type_id = 1, 2, 3... con el nombre ("Regulation", "Directive"...)

JOIN los conecta para que cada documento tenga el NOMBRE de su tipo, no solo el número.
```

In [13]:
# Sin JOIN: vemos type_id = 1, 2... pero no sabemos qué significan
sql("""
    SELECT celex_number, title, type_id
    FROM fact_documents
    LIMIT 3
""")

  celex_number                                              title  type_id
0   32019R0631  CO2 emission performance standards for new pas...        1
1   32019L0790  Directive on copyright in the Digital Single M...        2
2   32019L0882                         European Accessibility Act        2

In [14]:
# Con JOIN: conectamos con dim_document_type para ver el nombre del tipo
sql("""
    SELECT
        f.celex_number,            -- 'f' es un alias para fact_documents (para no escribir el nombre completo)
        f.title,
        dt.type_name               -- 'dt' es un alias para dim_document_type
    FROM fact_documents f          -- tabla principal, la llamamos 'f'
    JOIN dim_document_type dt      -- conectamos con dim_document_type, la llamamos 'dt'
        ON f.type_id = dt.type_id  -- la conexión: donde type_id coincida en ambas tablas
    LIMIT 5
""")
# Ahora en vez de type_id = 1, vemos type_name = 'Regulation'

  celex_number                                              title   type_name
0   32019R0631  CO2 emission performance standards for new pas...  Regulation
1   32019L0790  Directive on copyright in the Digital Single M...   Directive
2   32019L0882                         European Accessibility Act   Directive
3   32019R0881  ENISA and ICT cybersecurity certification (Cyb...  Regulation
4   32019L0944  Common rules for the internal market for elect...   Directive

In [15]:
# Podemos hacer JOIN con varias tablas a la vez
# Aquí conectamos: documentos → tipo + institución + fecha
sql("""
    SELECT
        f.title,                   -- título del documento
        dt.type_name,              -- nombre del tipo (Regulation, Directive...)
        i.institution_name,        -- nombre de la institución que lo publicó
        d.full_date                -- fecha completa de publicación
    FROM fact_documents f                              -- tabla central
    JOIN dim_document_type dt ON f.type_id = dt.type_id          -- conectar con tipos
    JOIN dim_institution i ON f.institution_id = i.institution_id -- conectar con instituciones
    JOIN dim_date d ON f.publication_date_key = d.date_key       -- conectar con fechas
    ORDER BY d.full_date DESC      -- más recientes primero
    LIMIT 10
""")

,title,type_name,institution_name,full_date
0,European Media Freedom Act (implementing measu...,Regulation,European Commission,2025-04-01
1,Directive on combating violence against women,Directive,European Parliament and Council (co-decision),2025-03-20
2,Soil Monitoring and Resilience Directive,Directive,European Parliament and Council (co-decision),2025-03-12
3,EU Space Law regulation,Regulation,European Parliament and Council (co-decision),2025-02-28
4,Anti-Money Laundering Authority (AMLA) operati...,Regulation,European Parliament and Council (co-decision),2025-02-05
5,Accessibility requirements for financial servi...,Regulation,European Commission,2025-01-15
6,Packaging and Packaging Waste Regulation,Regulation,European Parliament and Council (co-decision),2024-11-18
7,Critical Raw Materials Act,Regulation,European Parliament and Council (co-decision),2024-07-23
8,Artificial Intelligence Act (AI Act),Regulation,European Parliament and Council (co-decision),2024-07-13
9,Cyber Resilience Act,Regulation,European Parliament and Council (co-decision),2024-07-12

In [ ]:
# LEFT JOIN: incluye documentos aunque NO tengan coincidencia
# Aquí vemos cuántas veces se cita cada documento
# LEFT JOIN porque hay documentos que NADIE cita (queremos verlos también, con 0)
sql("""
    SELECT
        f.title,
        COUNT(dr.source_document_id) AS veces_citado  -- cuenta cuántos documentos lo citan
    FROM fact_documents f
    LEFT JOIN document_references dr                   -- LEFT = incluir documentos sin citas
        ON f.document_id = dr.target_document_id       -- buscar en la columna 'target' (el citado)
    GROUP BY f.title                                   -- agrupar por documento
    ORDER BY veces_citado ASC                         -- más citados primero
    LIMIT 10
""")

                                               title  veces_citado
0             EU Taxonomy for sustainable activities             3
1  ENISA and ICT cybersecurity certification (Cyb...             2
2  Corporate Sustainability Reporting Directive (...             2
3                               European Climate Law             2
4         Markets in Crypto-Assets Regulation (MiCA)             2
5      Ecodesign for Sustainable Products Regulation             2
6                 Horizon Europe Framework Programme             2
7               Artificial Intelligence Act (AI Act)             2
8                       European Data Governance Act             1
9  Promoting fairness and transparency for online...             1

---
## 6. Nuestro Star Schema — El modelo de datos EUR-Lex

Ahora que sabes SELECT, WHERE, GROUP BY y JOIN, puedes entender el diseño de nuestra base de datos.

### ¿Qué es un Star Schema?

Es una forma de organizar datos para análisis. Tiene forma de estrella:

```
               dim_date (fechas)
                    │
dim_topic ──── fact_documents ──── dim_institution
  (temas)      (tabla central)      (instituciones)
                    │
              dim_document_type
                (tipos de doc)
```

**Centro (FACT):** `fact_documents` — cada fila es un documento publicado. Contiene números medibles (artículos, longitud de texto, etc.)

**Puntas (DIMENSIONS):** tablas pequeñas que describen el contexto (quién, cuándo, qué tipo, sobre qué tema)

**¿Por qué este diseño?** Porque las preguntas analíticas siempre son:
- "¿Cuántos **documentos** (fact) publicó la **Comisión** (dimension) en **2023** (dimension) sobre **medio ambiente** (dimension)?"
- Siempre: fact → dimension, un solo salto de JOIN

In [20]:
# Explorar las dimensiones
print("=== Tipos de documento ===")
display(sql("SELECT type_code, type_name FROM dim_document_type"))

print("\n=== Instituciones ===")
display(sql("SELECT institution_code, institution_name FROM dim_institution"))

print("\n=== Temas ===")
display(sql("SELECT topic_code, topic_name, category FROM dim_topic"))

=== Tipos de documento ===

  type_code       type_name
0       REG      Regulation
1       DIR       Directive
2       DEC        Decision
3       REC  Recommendation
4       OPI         Opinion

=== Instituciones ===

  institution_code                               institution_name
0               EP                            European Parliament
1             CONS                  Council of the European Union
2              COM                            European Commission
3              ECB                          European Central Bank
4             CJEU         Court of Justice of the European Union
5              ECA                     European Court of Auditors
6          EP_CONS  European Parliament and Council (co-decision)

=== Temas ===

   topic_code                      topic_name        category
0         ENV         Environment and Climate  Sustainability
1         FIN  Financial Services and Banking         Economy
2         DIG  Digital Economy and Technology      Technology
3         TRA          Transport and Mobility  Infrastructure
4         ENE                          Energy  Infrastructure
5         AGR       Agriculture and Fisheries  Primary Sector
6         HEA          Health and Food Safety          Social
7         JUS        Justice and Home Affairs      Governance
8         TRD               Trade and Customs         Economy
9         LAB    Employment and Social Policy          Social
10        DEF            Defence and Security      Governance
11        EDU          Education and Research          Social

In [21]:
# Pregunta analítica: ¿Cuántos documentos por año y tipo?
# Esto combina JOIN + GROUP BY
sql("""
    SELECT
        d.year,                    -- el año (viene de dim_date)
        dt.type_name,              -- el tipo (viene de dim_document_type)
        COUNT(*) AS num_docs       -- cuántos documentos
    FROM fact_documents f          -- empezamos por la tabla central
    JOIN dim_date d                -- conectamos con fechas
        ON f.publication_date_key = d.date_key
    JOIN dim_document_type dt      -- conectamos con tipos
        ON f.type_id = dt.type_id
    GROUP BY d.year, dt.type_name  -- agrupamos por año Y tipo
    ORDER BY d.year, num_docs DESC -- ordenar por año, luego por cantidad
""")

    year   type_name  num_docs
0   2019  Regulation         4
1   2019   Directive         4
2   2020  Regulation         6
3   2020   Directive         2
4   2021  Regulation         8
5   2022  Regulation         6
6   2022   Directive         2
7   2023  Regulation         7
8   2023   Directive         3
9   2024  Regulation         8
10  2024   Directive         2
11  2025  Regulation         4
12  2025   Directive         2

In [22]:
# Pregunta: ¿Cuáles son los 5 temas con más documentos?
# Necesitamos la bridge table porque un documento puede tener VARIOS temas
# fact_documents → bridge_document_topic → dim_topic
sql("""
    SELECT
        t.topic_name,              -- nombre del tema
        t.category,                -- categoría del tema
        COUNT(*) AS num_docs       -- cuántos documentos tratan este tema
    FROM bridge_document_topic bt  -- tabla puente (conecta documentos con temas)
    JOIN dim_topic t               -- conectamos con la tabla de temas
        ON bt.topic_id = t.topic_id
    GROUP BY t.topic_name, t.category  -- agrupamos por tema
    ORDER BY num_docs DESC         -- más documentos primero
    LIMIT 5                        -- solo los top 5
""")

                       topic_name        category  num_docs
0  Digital Economy and Technology      Technology        21
1         Environment and Climate  Sustainability        18
2  Financial Services and Banking         Economy        15
3        Justice and Home Affairs      Governance         9
4               Trade and Customs         Economy         5

---
## 7. Window Functions — El concepto clave

### ¿Qué problema resuelven?

Con `GROUP BY`, las filas se **colapsan**: 58 documentos → 7 años. Pierdes el detalle individual.

Las **window functions** calculan algo sobre un grupo de filas pero **SIN colapsar**. Cada fila mantiene su identidad y además tiene el cálculo del grupo al lado.

### Analogía
Imagina una clase de 30 alumnos:
- `GROUP BY` = te da LA NOTA MEDIA de la clase (1 número, pierdes las notas individuales)
- `Window Function` = te da una tabla con CADA alumno, SU nota, Y la media de la clase al lado

### Sintaxis
```sql
funcion() OVER (
    PARTITION BY columna   -- divide las filas en grupos (opcional)
    ORDER BY columna       -- ordena dentro de cada grupo (opcional)
)
```

- **`OVER()`** = es lo que convierte una función normal en window function
- **`PARTITION BY`** = como GROUP BY, pero sin colapsar filas
- **`ORDER BY`** dentro del OVER = define el orden para funciones como ROW_NUMBER o LAG

In [23]:
# EJEMPLO SIMPLE: comparar GROUP BY vs Window Function

# Con GROUP BY: colapsa a una fila por tipo
print("=== GROUP BY (colapsa filas) ===")
display(sql("""
    SELECT
        type_id,
        AVG(article_count)::INTEGER AS media_articulos
    FROM fact_documents
    GROUP BY type_id
"""))

# Con Window Function: cada fila conserva su identidad + tiene la media al lado
print("\n=== WINDOW FUNCTION (mantiene todas las filas) ===")
display(sql("""
    SELECT
        title,                     -- cada documento individual
        type_id,
        article_count,             -- SU número de artículos
        AVG(article_count) OVER (  -- la media...
            PARTITION BY type_id   -- ...de los documentos DEL MISMO TIPO
        )::INTEGER AS media_del_tipo
    FROM fact_documents
    ORDER BY type_id, article_count DESC
    LIMIT 15
"""))

=== GROUP BY (colapsa filas) ===

   type_id  media_articulos
0        1               48
1        2               33

=== WINDOW FUNCTION (mantiene todas las filas) ===

,title,type_id,article_count,media_del_tipo
0,Markets in Crypto-Assets Regulation (MiCA),1,149,48
1,CAP Strategic Plans regulation,1,148,48
2,Common Provisions Regulation for EU funds 2021...,1,115,48
3,Artificial Intelligence Act (AI Act),1,113,48
4,"Financing, management and monitoring of the CAP",1,102,48
5,Digital Services Act,1,93,48
6,European Health Data Space regulation,1,72,48
7,ENISA and ICT cybersecurity certification (Cyb...,1,69,48
8,Ecodesign for Sustainable Products Regulation,1,68,48
9,Packaging and Packaging Waste Regulation,1,65,48
10,Cyber Resilience Act,1,58,48
11,EU Space Law regulation,1,55,48
12,Horizon Europe implementation,1,55,48
13,Digital Markets Act,1,54,48
14,European Crowdfunding Service Providers regula...,1,51,48

### 7.1 ROW_NUMBER — Numerar filas dentro de un grupo

`ROW_NUMBER()` asigna un número secuencial (1, 2, 3...) a cada fila dentro de su partición.

**Uso práctico:** Seleccionar "el primero de cada grupo" (el documento más reciente de cada tema, el más largo de cada tipo, etc.)

In [24]:
# Numerar documentos por article_count dentro de cada tipo
sql("""
    SELECT
        dt.type_name,                  -- tipo de documento
        f.title,                       -- título
        f.article_count,               -- número de artículos
        ROW_NUMBER() OVER (            -- asignar número de fila...
            PARTITION BY dt.type_name   -- ...reiniciando el contador para cada tipo
            ORDER BY f.article_count DESC  -- ...ordenando de mayor a menor artículos
        ) AS ranking                   -- el resultado se llama 'ranking'
    FROM fact_documents f
    JOIN dim_document_type dt ON f.type_id = dt.type_id
    ORDER BY dt.type_name, ranking
""")
# Resultado: dentro de 'Regulation', el doc con más artículos tiene ranking=1,
# el siguiente ranking=2, etc. Lo mismo para 'Directive', etc.

,type_name,title,article_count,ranking
0,Directive,Common rules for the internal market for elect...,72,1
1,Directive,European Accessibility Act,45,2
2,Directive,General Product Safety Regulation,44,3
3,Directive,Energy Efficiency Directive (recast),40,4
4,Directive,Renewable Energy Directive (RED III),38,5
5,Directive,Preventive restructuring frameworks and discha...,38,6
6,Directive,Directive on copyright in the Digital Single M...,32,7
7,Directive,Corporate Sustainability Due Diligence Directi...,30,8
8,Directive,Representative actions for the protection of c...,28,9
9,Directive,Soil Monitoring and Resilience Directive,28,10
10,Directive,Directive on combating violence against women,25,11
11,Directive,Quality of water intended for human consumptio...,23,12
12,Directive,Right to Repair Directive,22,13
13,Directive,Corporate Sustainability Reporting Directive (...,18,14
14,Directive,AI Liability Directive,18,15
15,Regulation,Markets in Crypto-Assets Regulation (MiCA),149,1
16,Regulation,CAP Strategic Plans regulation,148,2
17,Regulation,Common Provisions Regulation for EU funds 2021...,115,3
18,Regulation,Artificial Intelligence Act (AI Act),113,4
19,Regulation,"Financing, management and monitoring of the CAP",102,5
20,Regulation,Digital Services Act,93,6
21,Regulation,European Health Data Space regulation,72,7
22,Regulation,ENISA and ICT cybersecurity certification (Cyb...,69,8
23,Regulation,Ecodesign for Sustainable Products Regulation,68,9
24,Regulation,Packaging and Packaging Waste Regulation,65,10
25,Regulation,Cyber Resilience Act,58,11
26,Regulation,Horizon Europe implementation,55,12
27,Regulation,EU Space Law regulation,55,13
28,Regulation,Digital Markets Act,54,14
29,Regulation,European Crowdfunding Service Providers regula...,51,15
30,Regulation,Data Act,50,16
31,Regulation,Horizon Europe Framework Programme,48,17
32,Regulation,Critical Raw Materials Act,47,18
33,Regulation,European Digital Identity (eIDAS 2),45,19
34,Regulation,European Green Bonds standard,42,20
35,Regulation,Net-Zero Industry Act,42,21
36,Regulation,Anti-Money Laundering Authority (AMLA) operati...,38,22
37,Regulation,European Data Governance Act,38,23
38,Regulation,Carbon Border Adjustment Mechanism (CBAM),36,24
39,Regulation,Carbon Border Adjustment Mechanism (pilot prov...,36,25
40,Regulation,Euro 7 motor vehicle emission standards,35,26
41,Regulation,Deforestation-free products regulation,34,27
42,Regulation,European Chips Act (implementing regulation),28,28
43,Regulation,EU Taxonomy for sustainable activities,27,29
44,Regulation,CO2 emission performance standards for new pas...,25,30
45,Regulation,European Maritime Single Window environment,24,31
46,Regulation,Markets in Crypto-Assets (MiCA) - implementing...,22,32
47,Regulation,European Institute of Innovation and Technolog...,22,33
48,Regulation,DLT Pilot Regime for market infrastructures,20,34
49,Regulation,Accessibility requirements for financial servi...,20,35
50,Regulation,European Media Freedom Act (implementing measu...,18,36
51,Regulation,Promoting fairness and transparency for online...,18,37
52,Regulation,Energy labelling framework regulation,16,38
53,Regulation,Minimum requirements for water reuse,15,39
54,Regulation,European Climate Law,15,40
55,Regulation,European instrument for temporary support (SURE),12,41
56,Regulation,General regime of conditionality for the prote...,10,42
57,Regulation,European Union Recovery Instrument,10,43

In [25]:
# PATRÓN CLAVE: "top 1 por grupo" — el documento más reciente de cada tema
# Esto se usa CONSTANTEMENTE en ETL pipelines
#
# Estrategia:
#   1. ROW_NUMBER para numerar documentos por fecha dentro de cada tema
#   2. Filtrar solo los que tienen número 1 (el más reciente)
#
# Pero no podemos poner WHERE rn = 1 directamente porque SQL evalúa
# WHERE ANTES que las window functions. Solución: usar una subquery o CTE.
sql("""
    SELECT topic_name, titulo, fecha
    FROM (
        -- Subquery: primero calculamos el ranking
        SELECT
            t.topic_name,
            f.title AS titulo,
            d.full_date AS fecha,
            ROW_NUMBER() OVER (
                PARTITION BY t.topic_id        -- un grupo por cada tema
                ORDER BY d.full_date DESC      -- el más reciente primero
            ) AS rn
        FROM fact_documents f
        JOIN dim_date d ON f.publication_date_key = d.date_key
        JOIN bridge_document_topic bt ON f.document_id = bt.document_id
        JOIN dim_topic t ON bt.topic_id = t.topic_id
    ) sub                                      -- 'sub' es el alias de la subquery
    WHERE rn = 1                               -- solo el documento #1 de cada tema
    ORDER BY fecha DESC
""")

,topic_name,titulo,fecha
0,Digital Economy and Technology,European Media Freedom Act (implementing measu...,2025-04-01
1,Justice and Home Affairs,Directive on combating violence against women,2025-03-20
2,Employment and Social Policy,Directive on combating violence against women,2025-03-20
3,Agriculture and Fisheries,Soil Monitoring and Resilience Directive,2025-03-12
4,Environment and Climate,Soil Monitoring and Resilience Directive,2025-03-12
5,Defence and Security,EU Space Law regulation,2025-02-28
6,Financial Services and Banking,Anti-Money Laundering Authority (AMLA) operati...,2025-02-05
7,Trade and Customs,Critical Raw Materials Act,2024-07-23
8,Health and Food Safety,European Health Data Space regulation,2024-04-24
9,Energy,Net-Zero Industry Act,2024-04-20
10,Transport and Mobility,Euro 7 motor vehicle emission standards,2023-11-13
11,Education and Research,Horizon Europe implementation,2021-04-28

### 7.2 RANK vs DENSE_RANK vs ROW_NUMBER

¿Qué pasa cuando hay empates (mismos valores)?

| Función | Empates | Ejemplo con empate en posición 2 |
|---------|---------|-----------------------------------|
| `ROW_NUMBER` | Los ignora, asigna números únicos | 1, 2, 3, 4 |
| `RANK` | Mismo número a empates, luego salta | 1, 2, 2, 4 (salta el 3) |
| `DENSE_RANK` | Mismo número a empates, NO salta | 1, 2, 2, 3 (no salta) |

In [26]:
# Comparar las tres funciones
sql("""
    SELECT
        title,
        article_count,
        ROW_NUMBER() OVER (ORDER BY article_count DESC) AS row_num,    -- siempre único
        RANK()       OVER (ORDER BY article_count DESC) AS rank,       -- empate + salto
        DENSE_RANK() OVER (ORDER BY article_count DESC) AS dense_rank  -- empate sin salto
    FROM fact_documents
    ORDER BY article_count DESC
    LIMIT 15
""")

,title,article_count,row_num,rank,dense_rank
0,Markets in Crypto-Assets Regulation (MiCA),149,1,1,1
1,CAP Strategic Plans regulation,148,2,2,2
2,Common Provisions Regulation for EU funds 2021...,115,3,3,3
3,Artificial Intelligence Act (AI Act),113,4,4,4
4,"Financing, management and monitoring of the CAP",102,5,5,5
5,Digital Services Act,93,6,6,6
6,Common rules for the internal market for elect...,72,7,7,7
7,European Health Data Space regulation,72,8,7,7
8,ENISA and ICT cybersecurity certification (Cyb...,69,9,9,8
9,Ecodesign for Sustainable Products Regulation,68,10,10,9
10,Packaging and Packaging Waste Regulation,65,11,11,10
11,Cyber Resilience Act,58,12,12,11
12,Horizon Europe implementation,55,13,13,12
13,EU Space Law regulation,55,14,13,12
14,Digital Markets Act,54,15,15,13

### 7.3 LAG y LEAD — Mirar filas anteriores o siguientes

- **`LAG(columna, N)`** = devuelve el valor de la fila N posiciones ANTES
- **`LEAD(columna, N)`** = devuelve el valor de la fila N posiciones DESPUÉS

Si no especificas N, es 1 (la fila inmediatamente anterior/siguiente).

**Uso práctico:** Calcular cambios respecto al período anterior ("este mes vs. el mes pasado").

In [27]:
# Ejemplo simple: cada documento y el título del documento ANTERIOR (por fecha)
sql("""
    SELECT
        f.title AS documento_actual,
        d.full_date AS fecha,
        LAG(f.title) OVER (            -- el título...
            ORDER BY d.full_date       -- ...de la fila anterior ordenando por fecha
        ) AS documento_anterior
    FROM fact_documents f
    JOIN dim_date d ON f.publication_date_key = d.date_key
    ORDER BY d.full_date
    LIMIT 10
""")
# La primera fila tiene NULL en 'documento_anterior' porque no hay fila antes de ella

,documento_actual,fecha,documento_anterior
0,CO2 emission performance standards for new pas...,2019-04-17,None
1,Directive on copyright in the Digital Single M...,2019-05-17,CO2 emission performance standards for new pas...
2,Common rules for the internal market for elect...,2019-06-14,Directive on copyright in the Digital Single M...
3,ENISA and ICT cybersecurity certification (Cyb...,2019-06-17,Common rules for the internal market for elect...
4,European Accessibility Act,2019-06-17,ENISA and ICT cybersecurity certification (Cyb...
5,Preventive restructuring frameworks and discha...,2019-06-26,European Accessibility Act
6,European Maritime Single Window environment,2019-07-20,Preventive restructuring frameworks and discha...
7,Promoting fairness and transparency for online...,2019-07-20,European Maritime Single Window environment
8,European instrument for temporary support (SURE),2020-05-19,Promoting fairness and transparency for online...
9,EU Taxonomy for sustainable activities,2020-06-22,European instrument for temporary support (SURE)

In [28]:
# Caso práctico: documentos por año, comparando con el año anterior
# Primero agrupamos por año (GROUP BY), luego usamos LAG sobre el resultado
sql("""
    SELECT
        year,                          -- el año
        num_docs,                      -- documentos de este año
        LAG(num_docs) OVER (           -- documentos del año ANTERIOR
            ORDER BY year
        ) AS docs_anio_anterior,
        num_docs - LAG(num_docs) OVER (  -- la diferencia
            ORDER BY year
        ) AS cambio
    FROM (
        -- Subquery: contar documentos por año
        SELECT d.year, COUNT(*) AS num_docs
        FROM fact_documents f
        JOIN dim_date d ON f.publication_date_key = d.date_key
        GROUP BY d.year
    ) por_anio
    ORDER BY year
""")

   year  num_docs  docs_anio_anterior  cambio
0  2019         8                 NaN     NaN
1  2020         8                 8.0     0.0
2  2021         8                 8.0     0.0
3  2022         8                 8.0     0.0
4  2023        10                 8.0     2.0
5  2024        10                10.0     0.0
6  2025         6                10.0    -4.0

### 7.4 SUM, AVG, COUNT con OVER — Acumulados y totales

Las funciones de agregación (`SUM`, `AVG`, `COUNT`) también pueden ser window functions.

```sql
-- Sin ORDER BY en OVER: calcula sobre TODA la partición (total)
SUM(col) OVER ()                    -- suma total de toda la tabla
SUM(col) OVER (PARTITION BY grupo)  -- suma total de cada grupo

-- Con ORDER BY en OVER: calcula de forma ACUMULADA (running total)
SUM(col) OVER (ORDER BY fecha)      -- suma acumulada hasta cada fila
```

In [29]:
# Ejemplo 1: Cada documento con el TOTAL de su tipo al lado
# Esto permite calcular el porcentaje que cada documento representa
sql("""
    SELECT
        dt.type_name,
        f.title,
        f.article_count,
        SUM(f.article_count) OVER (           -- suma total de artículos...
            PARTITION BY dt.type_name          -- ...del mismo tipo de documento
        ) AS total_articulos_del_tipo,
        ROUND(
            100.0 * f.article_count            -- porcentaje = (mi valor / total) * 100
            / SUM(f.article_count) OVER (PARTITION BY dt.type_name),
            1                                  -- 1 decimal
        ) AS porcentaje_del_tipo
    FROM fact_documents f
    JOIN dim_document_type dt ON f.type_id = dt.type_id
    ORDER BY dt.type_name, f.article_count DESC
    LIMIT 15
""")

,type_name,title,article_count,total_articulos_del_tipo,porcentaje_del_tipo
0,Directive,Common rules for the internal market for elect...,72,501,14.4
1,Directive,European Accessibility Act,45,501,9.0
2,Directive,General Product Safety Regulation,44,501,8.8
3,Directive,Energy Efficiency Directive (recast),40,501,8.0
4,Directive,Renewable Energy Directive (RED III),38,501,7.6
5,Directive,Preventive restructuring frameworks and discha...,38,501,7.6
6,Directive,Directive on copyright in the Digital Single M...,32,501,6.4
7,Directive,Corporate Sustainability Due Diligence Directi...,30,501,6.0
8,Directive,Representative actions for the protection of c...,28,501,5.6
9,Directive,Soil Monitoring and Resilience Directive,28,501,5.6
10,Directive,Directive on combating violence against women,25,501,5.0
11,Directive,Quality of water intended for human consumptio...,23,501,4.6
12,Directive,Right to Repair Directive,22,501,4.4
13,Directive,Corporate Sustainability Reporting Directive (...,18,501,3.6
14,Directive,AI Liability Directive,18,501,3.6

In [30]:
# Ejemplo 2: Acumulado (running total) de documentos publicados por año
sql("""
    SELECT
        year,
        num_docs,
        SUM(num_docs) OVER (               -- suma acumulada...
            ORDER BY year                  -- ...año a año (de menor a mayor)
        ) AS total_acumulado               -- cada fila muestra el total HASTA ese año
    FROM (
        SELECT d.year, COUNT(*) AS num_docs
        FROM fact_documents f
        JOIN dim_date d ON f.publication_date_key = d.date_key
        GROUP BY d.year
    ) por_anio
    ORDER BY year
""")
# 2019: 8 docs → acumulado = 8
# 2020: 8 docs → acumulado = 16 (8+8)
# 2021: 8 docs → acumulado = 24 (16+8)
# etc.

   year  num_docs  total_acumulado
0  2019         8              8.0
1  2020         8             16.0
2  2021         8             24.0
3  2022         8             32.0
4  2023        10             42.0
5  2024        10             52.0
6  2025         6             58.0

### 7.5 NTILE — Dividir en buckets

`NTILE(N)` divide las filas en N grupos de tamaño aproximadamente igual.

- `NTILE(4)` = cuartiles (25% en cada grupo)
- `NTILE(10)` = deciles (10% en cada grupo)

**Uso práctico:** Clasificar datos en categorías (documentos simples/complejos, clientes por gasto, etc.)

In [31]:
# Clasificar documentos en 4 niveles de complejidad por número de artículos
sql("""
    SELECT
        title,
        article_count,
        NTILE(4) OVER (                    -- dividir en 4 grupos...
            ORDER BY article_count         -- ...ordenados de menor a mayor artículos
        ) AS cuartil,                      -- 1=más simple, 4=más complejo
        CASE NTILE(4) OVER (ORDER BY article_count)
            WHEN 1 THEN 'Simple'           -- CASE = como un if/elif en Python
            WHEN 2 THEN 'Moderado'
            WHEN 3 THEN 'Complejo'
            WHEN 4 THEN 'Muy Complejo'
        END AS nivel_complejidad           -- END cierra el CASE
    FROM fact_documents
    ORDER BY article_count DESC
    LIMIT 15
""")

,title,article_count,cuartil,nivel_complejidad
0,Markets in Crypto-Assets Regulation (MiCA),149,4,Muy Complejo
1,CAP Strategic Plans regulation,148,4,Muy Complejo
2,Common Provisions Regulation for EU funds 2021...,115,4,Muy Complejo
3,Artificial Intelligence Act (AI Act),113,4,Muy Complejo
4,"Financing, management and monitoring of the CAP",102,4,Muy Complejo
5,Digital Services Act,93,4,Muy Complejo
6,European Health Data Space regulation,72,4,Muy Complejo
7,Common rules for the internal market for elect...,72,4,Muy Complejo
8,ENISA and ICT cybersecurity certification (Cyb...,69,4,Muy Complejo
9,Ecodesign for Sustainable Products Regulation,68,4,Muy Complejo
10,Packaging and Packaging Waste Regulation,65,4,Muy Complejo
11,Cyber Resilience Act,58,4,Muy Complejo
12,Horizon Europe implementation,55,4,Muy Complejo
13,EU Space Law regulation,55,4,Muy Complejo
14,Digital Markets Act,54,3,Complejo

---
## 8. CTEs — Common Table Expressions

Un **CTE** es una subquery con nombre. En vez de anidar subqueries (difícil de leer), le das un nombre y la usas como si fuera una tabla temporal.

```sql
WITH nombre_del_cte AS (
    -- tu query aquí
)
SELECT * FROM nombre_del_cte
```

**¿Por qué usar CTEs?**
1. **Legibilidad:** divides una query compleja en pasos con nombre
2. **Reutilización:** puedes usar el CTE varias veces en la misma query
3. **Mantenibilidad:** cada paso se puede entender y depurar por separado

**Analogía Python:** es como definir variables intermedias:
```python
# Sin CTEs (todo anidado, difícil de leer):
resultado = procesar(filtrar(cargar(datos)))

# Con CTEs (pasos claros):
cargado = cargar(datos)
filtrado = filtrar(cargado)
resultado = procesar(filtrado)
```

In [33]:
# Ejemplo: ¿Qué temas tienen actividad legislativa acelerándose?
# (más documentos en 2023-2025 que en 2019-2021)
#
# Lo hacemos en 3 pasos con CTEs encadenados:
sql("""
    -- PASO 1: Contar documentos por tema y año
    WITH docs_por_tema_anio AS (
        SELECT
            t.topic_name,
            d.year,
            COUNT(*) AS num_docs
        FROM fact_documents f
        JOIN dim_date d ON f.publication_date_key = d.date_key
        JOIN bridge_document_topic bt ON f.document_id = bt.document_id
        JOIN dim_topic t ON bt.topic_id = t.topic_id
        GROUP BY t.topic_name, d.year
    ),

    -- PASO 2: Separar en período temprano y reciente
    comparacion AS (
        SELECT
            topic_name,
            -- SUM con CASE: suma condicional
            -- "suma num_docs SOLO cuando year está entre 2019 y 2021, sino suma 0"
            SUM(CASE WHEN year BETWEEN 2019 AND 2021 THEN num_docs ELSE 0 END) AS periodo_temprano,
            SUM(CASE WHEN year BETWEEN 2023 AND 2025 THEN num_docs ELSE 0 END) AS periodo_reciente
        FROM docs_por_tema_anio
        GROUP BY topic_name
    )

    -- PASO 3: Calcular la diferencia y clasificar
    SELECT
        topic_name AS tema,
        periodo_temprano,
        periodo_reciente,
        periodo_reciente - periodo_temprano AS aceleracion,
        CASE
            WHEN periodo_reciente > periodo_temprano THEN 'ACELERANDO'
            WHEN periodo_reciente = periodo_temprano THEN 'ESTABLE'
            ELSE 'DESACELERANDO'
        END AS tendencia
    FROM comparacion
    ORDER BY aceleracion DESC
""")

,tema,periodo_temprano,periodo_reciente,aceleracion,tendencia
0,Environment and Climate,5.0,12.0,7.0,ACELERANDO
1,Digital Economy and Technology,5.0,11.0,6.0,ACELERANDO
2,Justice and Home Affairs,3.0,5.0,2.0,ACELERANDO
3,Energy,1.0,3.0,2.0,ACELERANDO
4,Trade and Customs,2.0,3.0,1.0,ACELERANDO
5,Defence and Security,1.0,2.0,1.0,ACELERANDO
6,Transport and Mobility,2.0,1.0,-1.0,DESACELERANDO
7,Agriculture and Fisheries,2.0,1.0,-1.0,DESACELERANDO
8,Health and Food Safety,2.0,1.0,-1.0,DESACELERANDO
9,Employment and Social Policy,2.0,1.0,-1.0,DESACELERANDO
10,Education and Research,3.0,0.0,-3.0,DESACELERANDO
11,Financial Services and Banking,8.0,4.0,-4.0,DESACELERANDO

---
## 9. CTEs Recursivos — Recorrer grafos en SQL

Un CTE **recursivo** se referencia a sí mismo. Tiene dos partes:

```sql
WITH RECURSIVE nombre AS (
    -- PARTE 1: Caso base (el punto de partida)
    SELECT ... WHERE id = punto_inicio
    
    UNION ALL
    
    -- PARTE 2: Paso recursivo (se expande desde lo anterior)
    SELECT ... FROM nombre JOIN otra_tabla ...
    WHERE profundidad < limite  -- IMPORTANTE: siempre poner un límite
)
SELECT * FROM nombre
```

**Conexión con ADIAC:** Esto es exactamente un BFS (Breadth-First Search):
- Caso base = nodo inicial
- Paso recursivo = explorar vecinos
- Límite de profundidad = equivalente al nivel del BFS

Es la versión SQL de lo que haremos en Neo4j con `MATCH path = (a)-[:REFERENCES*1..3]->(b)`

In [34]:
# Pregunta: ¿Qué documentos citan al AI Act, y qué documentos citan a esos?
# Es un BFS partiendo del AI Act, siguiendo las referencias
sql("""
    WITH RECURSIVE cadena AS (
        -- CASO BASE: empezamos por el AI Act
        SELECT
            f.document_id,             -- ID del documento
            f.celex_number,            -- código identificador
            f.title,                   -- título
            0 AS profundidad,          -- nivel 0 = el punto de partida
            f.title AS camino          -- el camino recorrido (para ver la cadena)
        FROM fact_documents f
        WHERE f.celex_number = '32024R1689'  -- filtrar: solo el AI Act

        UNION ALL

        -- PASO RECURSIVO: buscar documentos que citan a los del nivel anterior
        SELECT
            f.document_id,
            f.celex_number,
            f.title,
            c.profundidad + 1,         -- un nivel más profundo
            c.camino || ' → ' || f.title  -- concatenar al camino (|| = concatenar en SQL)
        FROM cadena c                  -- la tabla recursiva (el nivel anterior)
        JOIN document_references dr    -- tabla de referencias
            ON c.document_id = dr.target_document_id  -- buscar quién cita al doc actual
        JOIN fact_documents f          -- obtener datos del documento que cita
            ON dr.source_document_id = f.document_id
        WHERE c.profundidad < 3        -- LÍMITE: máximo 3 niveles (evitar bucles infinitos)
    )
    SELECT profundidad, celex_number, title, camino
    FROM cadena
    ORDER BY profundidad, celex_number
""")
# Nivel 0: AI Act (el punto de partida)
# Nivel 1: documentos que CITAN al AI Act (AI Liability, Cyber Resilience...)
# Nivel 2: documentos que citan a los del nivel 1
# etc.

,profundidad,celex_number,title,camino
0,0,32024R1689,Artificial Intelligence Act (AI Act),Artificial Intelligence Act (AI Act)
1,1,32024L1640,AI Liability Directive,Artificial Intelligence Act (AI Act) → AI Liab...
2,1,32024R1735,Cyber Resilience Act,Artificial Intelligence Act (AI Act) → Cyber R...

---
## 10. EXPLAIN ANALYZE — Entender cómo PostgreSQL ejecuta tu query

Cuando escribes una query, PostgreSQL no la ejecuta tal cual. Internamente decide:
- ¿Escaneo toda la tabla fila por fila? (**Seq Scan** — lento en tablas grandes)
- ¿Uso un índice para ir directo? (**Index Scan** — rápido)
- ¿Cómo hago los JOINs? (Hash Join, Nested Loop, Merge Join)

`EXPLAIN ANALYZE` te muestra estas decisiones + el tiempo real que tardó cada paso.

### Qué buscar en el output:
- **Seq Scan** en tablas grandes → probablemente necesitas un índice
- **actual time** → cuánto tardó en milisegundos
- **rows** → cuántas filas procesó (si es mucho más de lo esperado, hay un problema)

In [35]:
# Buscar por celex_number (TIENE índice único → debería ser Index Scan)
print("=== Búsqueda por celex_number (con índice) ===")
sql_explain("""
    SELECT * FROM fact_documents
    WHERE celex_number = '32024R1689'
""")
# Verás algo como: "Index Scan using fact_documents_celex_number_key"
# Eso significa que fue DIRECTO al registro, sin escanear toda la tabla

=== Búsqueda por celex_number (con índice) ===
Seq Scan on fact_documents  (cost=0.00..1.73 rows=1 width=84) (actual time=0.020..0.023 rows=1 loops=1)
  Filter: ((celex_number)::text = '32024R1689'::text)
  Rows Removed by Filter: 57
Planning Time: 0.113 ms
Execution Time: 0.044 ms

In [ ]:
# Buscar por título con LIKE (NO tiene índice → será Seq Scan)
print("=== Búsqueda por título con LIKE (sin índice) ===")
sql_explain("""
    SELECT * FROM fact_documents
    WHERE title LIKE '%Artificial%'
""")
# Verás: "Seq Scan" → tuvo que revisar TODAS las filas
# Con 58 filas no importa, pero con millones sería un problema

=== Búsqueda por título con LIKE (sin índice) ===
Seq Scan on fact_documents  (cost=0.00..1.73 rows=1 width=84) (actual time=0.018..0.021 rows=1 loops=1)
  Filter: (title ~~ '%Artificial%'::text)
  Rows Removed by Filter: 57
Planning Time: 0.071 ms
Execution Time: 0.031 ms

In [ ]:
# Query con JOIN: ver cómo PostgreSQL decide unir las tablas
print("=== Query con JOINs ===")
sql_explain("""
    SELECT t.topic_name, COUNT(*)
    FROM fact_documents f
    JOIN bridge_document_topic bt ON f.document_id = bt.document_id
    JOIN dim_topic t ON bt.topic_id = t.topic_id
    JOIN dim_date d ON f.publication_date_key = d.date_key
    WHERE d.year >= 2022
    GROUP BY t.topic_name
""")
# Aquí verás: Hash Join, Seq Scan (tablas pequeñas), y un Sort/GroupAggregate

=== Query con JOINs ===
HashAggregate  (cost=79.78..80.31 rows=53 width=426) (actual time=0.491..0.496 rows=11 loops=1)
  Group Key: t.topic_name
  Batches: 1  Memory Usage: 24kB
  ->  Nested Loop  (cost=5.53..79.51 rows=53 width=418) (actual time=0.191..0.471 rows=56 loops=1)
        ->  Hash Join  (cost=5.38..69.48 rows=53 width=4) (actual time=0.178..0.419 rows=56 loops=1)
              Hash Cond: (f.document_id = bt.document_id)
              ->  Hash Join  (cost=2.31..65.73 rows=33 width=4) (actual time=0.126..0.352 rows=34 loops=1)
                    Hash Cond: (d.date_key = f.publication_date_key)
                    ->  Seq Scan on dim_date d  (cost=0.00..53.96 rows=1461 width=4) (actual time=0.077..0.226 rows=1461 loops=1)
                          Filter: (year >= 2022)
                          Rows Removed by Filter: 1096
                    ->  Hash  (cost=1.58..1.58 rows=58 width=8) (actual time=0.018..0.019 rows=58 loops=1)
                          Buckets: 1024  Batches: 1  Memory Usage: 11kB
                          ->  Seq Scan on fact_documents f  (cost=0.00..1.58 rows=58 width=8) (actual time=0.004..0.010 rows=58 loops=1)
              ->  Hash  (cost=1.92..1.92 rows=92 width=8) (actual time=0.028..0.028 rows=92 loops=1)
                    Buckets: 1024  Batches: 1  Memory Usage: 12kB
                    ->  Seq Scan on bridge_document_topic bt  (cost=0.00..1.92 rows=92 width=8) (actual time=0.007..0.014 rows=92 loops=1)
        ->  Memoize  (cost=0.15..0.69 rows=1 width=422) (actual time=0.001..0.001 rows=1 loops=56)
              Cache Key: bt.topic_id
              Cache Mode: logical
              Hits: 45  Misses: 11  Evictions: 0  Overflows: 0  Memory Usage: 2kB
              ->  Index Scan using dim_topic_pkey on dim_topic t  (cost=0.14..0.68 rows=1 width=422) (actual time=0.002..0.002 rows=1 loops=11)
                    Index Cond: (topic_id = bt.topic_id)
Planning Time: 0.332 ms
Execution Time: 0.556 ms

---
## 11. Ejercicios

Intenta resolverlos tú. Si te atascas, avísame y te doy pistas progresivas.

In [ ]:
# EJERCICIO 1 (JOIN + GROUP BY):
# ¿Cuántos documentos publicó cada institución? Ordena de mayor a menor.
# Tablas: fact_documents, dim_institution
# Columna de unión: institution_id
#
# Tu query aquí:

In [ ]:
# EJERCICIO 2 (Window Function):
# Para cada documento, muestra su title, article_count,
# y cuántos artículos tiene el documento con MÁS artículos (MAX como window function).
# Así puedes ver cuán lejos está cada documento del máximo.
#
# Pista: MAX(article_count) OVER ()
# OVER () sin PARTITION BY = sobre TODA la tabla
#
# Tu query aquí:

In [ ]:
# EJERCICIO 3 (LAG):
# Para los documentos del tema 'Digital Economy and Technology' (topic_code = 'DIG'),
# muestra cada documento con su fecha y cuántos DÍAS pasaron desde el documento anterior.
#
# Pistas:
# - Necesitas JOINs: fact_documents → dim_date + bridge_document_topic → dim_topic
# - LAG(d.full_date) OVER (ORDER BY d.full_date) para la fecha anterior
# - Restar fechas en PostgreSQL: fecha1 - fecha2 = días entre ellas
#
# Tu query aquí:

In [ ]:
# EJERCICIO 4 (CTE + Window Function):
# Crea un ranking de temas por número total de artículos.
# Paso 1 (CTE): Suma article_count por topic_name
# Paso 2: Usa ROW_NUMBER() para rankear los temas
#
# Tu query aquí:

---
## Resumen — Qué aprendiste y dónde lo usarás

| Concepto SQL | Qué hace | Equivalente en el proyecto |
|-------------|----------|---------------------------|
| `SELECT / FROM / WHERE` | Leer y filtrar datos | Base de todo |
| `GROUP BY` + agregaciones | Resumir datos por grupos | PySpark: `groupBy().agg()` |
| `JOIN` | Combinar tablas | PySpark: `df.join()` |
| Star Schema | Modelo analítico (fact + dimensions) | El gold layer del pipeline PySpark |
| `ROW_NUMBER / RANK` | Numerar filas en un grupo | PySpark: `Window` + `row_number()` |
| `LAG / LEAD` | Comparar con fila anterior/siguiente | PySpark: `Window` + `lag()` |
| `SUM OVER` | Totales y acumulados sin colapsar | PySpark: `Window` + `sum()` |
| CTEs | Dividir queries complejas en pasos | PySpark: variables intermedias de DataFrames |
| CTEs Recursivos | Recorrer grafos (BFS) | Neo4j: `MATCH (a)-[:REF*1..3]->(b)` |
| `EXPLAIN ANALYZE` | Ver plan de ejecución y optimizar | Spark UI: stages, shuffles |

**Semana que viene:** PySpark — verás cómo todo esto se traduce a DataFrames distribuidos.